import { Metadata } from 'next';
import {
	Button,
	DestinationCards,
	DestinationHeader,
	Title,
	PlanTabs,
} from '@/components/ui';
import DUMMY_DESTINATIONS from 'app/data';
import { PlanTabsEnum } from '../../../constants';

import styles from './local.module.scss';

export const metadata: Metadata = {
	title: 'Local Destination - TravelPulse',
	description: 'Generated by create next app',
};

const LocalDestinationsPage = () => {
	return (
		<>
			<DestinationHeader
				title="Discover the power of International eSIM"
				subTitle="Explore the world without losing connection. Choose from
						hundreds of data plans and enjoy fast, seamless eSIM
						connectivity tailored for travelers and digital nomads."
			/>
			<main className={styles.localMain}>
				<Title position="center" size="size40">
					Popular destination
				</Title>

				<div className={styles.popularDestinationContainer}>
					<DestinationCards data={DUMMY_DESTINATIONS} />
				</div>

				<Title position="center" size="size40">
					Stay connected globally
				</Title>
				<Title
					position="center"
					size="size16"
					className={styles.subTitle}
				>
					Enjoy reliable service and uninterrupted data no matter
					where your journey takes you. TravelPulse has got you
					covered.
				</Title>

				<div className={styles.planTabsContainer}>
					<PlanTabs activePlan={PlanTabsEnum.Global} />
				</div>

				<div className={styles.popularDestinationContainer}>
					<Title size="size20">Local plans</Title>
					<DestinationCards
						data={DUMMY_DESTINATIONS}
						destinationType="local"
					/>
					<div className="text-center">
						<Button variant="outline" className={styles.seeAllBtn}>
							View all countries
						</Button>
					</div>
				</div>

				<div>
					<Title position="center" size="size35">
						Ready to get started?
					</Title>
					<Title
						position="center"
						size="size16"
						className={styles.getYourEsimSubTitle}
					>
						Get your eSIM installed in few steps and enjoy
						uninterrupted data where ever you are.
					</Title>

					<div className={styles.getStartedBtnContainer}>
						<Button size="lg">Get your eSIM now</Button>
					</div>
				</div>
			</main>
		</>
	);
};

export default LocalDestinationsPage;
