import { Metadata } from 'next';
import { DestinationHeader } from '@/components/ui';

// import styles from './local.module.scss';

export const metadata: Metadata = {
	title: 'Local Destination - TravelPulse',
	description: 'Generated by create next app',
};

const LocalDestinationsPage = () => {
	return (
		<>
			<DestinationHeader />
			<div>
				<h1>Local Destinations</h1>
				<p>Explore the best local destinations around you!</p>
			</div>
		</>
	);
};

export default LocalDestinationsPage;
